version: 1.6 #Пожалуйста не трогайте эту строчку!

messages:
  heal: '&aВы были вылечены!'
  dontplayerheal: '&cИгрок не найден!'
  NoPermisionheal: '&cУ вас нет прав!'
  NoPermisionhealconsole: '&cЭту команду могут использовать только игроки!'
  feed: '&aВы были накормлены!'
  NoPermisionfeed: '&cУ вас нет прав!'
  NoPermisionconsole: '&cЭту команду могут использовать только игроки!'
  dontplayerfeed: '&cИгрок не найден!'
  NoPermisionbc: '&cУ вас нет прав!'
  NoPermisionbcconsole: '&cУ вас нет прав!'
  Dontmessagebc: '&cПожалуйста напишите хотябы одну букву!'
  flyeffect: 'Ой! Пора в полет!'
  dontplayerflyeffect: '&cИгрок не найден!'
  NoPermisioneffectfly: '&cУ вас нет прав!'
  NoPermisionflyeffectconsole: '&cЭту команду могут использовать только игроки!'
  NoPermisionhelp: '&cУ вас нет прав!'
  NoPermisionmoder: '&cУ вас нет прав!'
plugin:
  Reloadplugin: '&aПлагин перезагружен!'
  NoPermisionreload: '&cУ вас нет прав!'

moder:
  message:
    on: 'f'
    off: 'd'
  bc:
    on: '&aMore-command &7| Игрок %player'
    off: '&c'
  job:
    on: "lp user %player% parent add moder-on"
    off: 'lp user %player% parent remove moder-off'

permissions:
  feed: 'more-command.feed'
  feed.others: 'more-command.feed.others'
  heal: 'more-command.heal'
  heal.others: 'more-command.heal.others'
  help: 'more-command.help'
  bc: 'more-command.bc'
  reload: 'more-command.reload'
  flyeffect: 'more-command.flyeffect'
  flyeffect.others: 'more-command.flyeffect.others'
  moder: 'more-command.moder.use'
broadcast:
  start: '%player'

