name: More-command
version: '1.6.1.2'
main: spigotmc.ru.morecommand.More_command
api-version: 1.14
commands:
  mc:
    description: Основная команда плагина
  gm:
    description: меняет режим игры
  heal:
    description: Полное востоновление здоровья игрока
  feed:
    description: Полное востоновление голода
  bc:
    description: Обьявление на весь сервер
  flyeffect:
    description: Пошутить над игроком левитацией
